# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87dc0e249ed9952b03d0925e236473a46e8925f9080c642676554ed5258fa9d754a97ae02b26419a84b2d3d96b324961d57610acc790b54d05a784ea5a090406

test:
  secret_key_base: 593e2219ddd362d1a88dac3f216ecd81171ae4aa6ffda80e9cda6baf7868d420b6ef0408b2a8c503373412076256b5c0708eb41c3df518cb152b2cbb6699f7bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
